server:
  port : 8084
spring:
  application:
    name : API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quizzes/**
        - id: INTERACTION-SERVICE
          uri: lb://INTERACTION-SERVICE
          predicates:
            - Path=/interactions/**
        

#eureka:
#  instance:
#    prefer-ip-address : true
#  client:
#    fetchRegistry : true
#    registerWithEureka : true
#    serviceUrl :
#      defaultZone : http://localhost:8761/eureka