server:
  port: 8081
spring:
  application:
    name: QUIZ-SERVICE
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.foedxgeoyetpchiqrtyo
    password: ChiruKed@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          timezone: UTC
  config:
    import: optional:configserver:http://localhost:8085
  jackson:
    serialization:
      fail-on-empty-beans: false
  
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
