server:
  port: 8083
spring:
  application:
    name: INTERACTION-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: quiz-website
  config:
    import: optional:configserver:http://localhost:8085
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
